theme: jekyll-theme-hacker
name: Master Data Science by Kien Tran
title: [Master Data Science by Kien Tran](https://master-data.science/)
description: Go with me on the journey of mastering Data Science
google_analytics: UA-65705806-5